spring:
  application:
    name: external-configuration-service
  cloud:
    config:
      server:
        git:
          uri: "git@github.com:kristofsteindl/external-codehunters-config.git"
          clone-on-start: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8080/eureka/