spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@cluster0.r3k2ajp.mongodb.net/kdb?retryWrites=true&w=majority
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
jwt:
  secret: ${JWT_SECRET:C0EDC2B9C12155C6DF60F929BEC2BAFE8F3986D5B7E9D232634ABD97EEF2B0E4}
  expiration-time: 3600 #1 hour