services:
  user-service:
    restart: always
    build: ./user-service
    depends_on:
      - service-discovery
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "9000:8080"
    networks: 
      - spring-cloud-demo
  
  service-discovery:
    restart: always
    build: ./service-discovery
    ports:
      - "9001:8080"
    networks:
      - spring-cloud-demo

  gateway-service:
    restart: always
    build: ./gateway-service
    depends_on:
      - user-service
      - service-discovery
    ports:
      - "9002:8080"
    networks:
      - spring-cloud-demo
  
  external-configuration-service:
#    restart: always
    build: ./external-configuration-service
    container_name: config_server
    volumes:
      - "/home/ksteindl/.ssh(copy):/root/.ssh"
    networks:
      - spring-cloud-demo
    ports:
      - "9003:8080"
    depends_on:
      - service-discovery
networks: 
  spring-cloud-demo: {}



