spring:
  application:
    name: service-discovery
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://service-discovery:8080/eureka/
  server:
    peer-node-read-timeout-ms: 500
    peer-node-connect-timeout-ms: 500
  dashboard:
    enabled: true